import { parse } from '../pattern/parser';
import { resolveRepeats } from '../pattern/resolve-repeats';
import type { CrochetAst, RawCrochetAst } from '../types';
import { expandPattern } from './expand';

// parser.ts is generated by ts-pegjs with a generic ParseFunction signature;
// centralizing the cast here keeps every call site's parse result simply typed.
//
// The two things a written pattern leaves to the reader are settled here rather
// than at each call site, so nothing downstream ever has to handle a round that
// is only a reference to another round, a beginning chain whose worth is still
// unknown, or a repeat whose count is still unknown.
export function parseChart(source: string): CrochetAst {
	return resolveRepeats(expandPattern(parse(source) as RawCrochetAst));
}
