import obsidianmd from 'eslint-plugin-obsidianmd';
import globals from 'globals';
import { globalIgnores, defineConfig } from 'eslint/config';

export default defineConfig(
	globalIgnores([
		'node_modules',
		'dist',
		'src/pattern/parser.ts', // generated by peggy/ts-pegjs
		'src/skill-content.ts', // generated by scripts/generate-skill-content.mjs

		'esbuild.config.mjs',
		'version-bump.mjs',
		'scripts',
		'versions.json',
		'main.js',
		'package.json',
		'package-lock.json',
		'tsconfig.json',
	]),
	{
		languageOptions: {
			globals: {
				...globals.browser,
			},
			parserOptions: {
				projectService: {
					allowDefaultProject: ['eslint.config.mts', 'manifest.json'],
				},
				tsconfigRootDir: import.meta.dirname,
				extraFileExtensions: ['.json'],
			},
		},
	},
	...obsidianmd.configs.recommended,
	{
		files: ['tests/**/*.ts'],
		rules: {
			'obsidianmd/prefer-create-el': 'off',
			// Tests run under Node/Vitest, not inside Obsidian's mobile-constrained
			// runtime, so reading fixture files with node:fs is fine here.
			'obsidianmd/no-nodejs-modules': 'off',
		},
	},
);
