import { parse } from './parser';
import { resolveRepeats } from './resolve-repeats';
import type { CrochetAst } from './types';

// parser.ts is generated by ts-pegjs with a generic ParseFunction signature;
// centralizing the cast here keeps every call site's parse result simply typed.
//
// Bare "rep" repeats are resolved here rather than at each call site, so
// nothing downstream ever has to handle a repeat whose count is still unknown.
export function parseChart(source: string): CrochetAst {
	return resolveRepeats(parse(source) as CrochetAst);
}
