import { parse } from './parser';
import type { CrochetAst } from './types';

// parser.ts is generated by ts-pegjs with a generic ParseFunction signature;
// centralizing the cast here keeps every call site's parse result simply typed.
export function parseChart(source: string): CrochetAst {
	return parse(source) as CrochetAst;
}
